'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.8.3928.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class document
    
    Private configurationField As documentConfiguration
    
    Private aliassetField As String
    
    Private pdmweidField As UShort
    
    '''<remarks/>
    Public Property configuration() As documentConfiguration
        Get
            Return Me.configurationField
        End Get
        Set
            Me.configurationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property aliasset() As String
        Get
            Return Me.aliassetField
        End Get
        Set
            Me.aliassetField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property pdmweid() As UShort
        Get
            Return Me.pdmweidField
        End Get
        Set
            Me.pdmweidField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class documentConfiguration
    
    Private attributeField() As documentConfigurationAttribute
    
    Private referencesField() As document

    Private nameField As String

    Private Function attr(StrName As String)
        For Each a As documentConfigurationAttribute In attributeField
            Select Case a.name.ToLower
                Case StrName.ToLower
                    Return a.value
            End Select
        Next
        Return Nothing
    End Function

    Public ReadOnly Property document_pdmweid As String
        Get
            Return attr("document pdmweid")
        End Get
    End Property

    Public ReadOnly Property originationdate
        Get
            Return attr("originationdate")
        End Get
    End Property

    Public ReadOnly Property revision As String
        Get
            Return attr("revision")
        End Get
    End Property

    Public ReadOnly Property number As String
        Get
            Return attr("number")
        End Get
    End Property

    Public ReadOnly Property description As String
        Get
            Return attr("description")
        End Get
    End Property

    Public ReadOnly Property project As String
        Get
            Return attr("project")
        End Get
    End Property

    Public ReadOnly Property material As String
        Get
            Return attr("material")
        End Get
    End Property
    Public ReadOnly Property finish As String
        Get
            Return attr("finish")
        End Get
    End Property
    Public ReadOnly Property author As String
        Get
            Return attr("author")
        End Get
    End Property
    Public ReadOnly Property weight As String
        Get
            Return attr("weight")
        End Get
    End Property
    Public ReadOnly Property process_4 As String
        Get
            Return attr("process 4")
        End Get
    End Property

    Public ReadOnly Property process_3 As String
        Get
            Return attr("process 3")
        End Get
    End Property

    Public ReadOnly Property process_2 As String
        Get
            Return attr("process 2")
        End Get
    End Property

    Public ReadOnly Property process_1 As String
        Get
            Return attr("process 1")
        End Get
    End Property

    Public ReadOnly Property cross_reference As String
        Get
            Return attr("cross reference")
        End Get
    End Property

    Public ReadOnly Property product_type As String
        Get
            Return attr("product type")
        End Get
    End Property

    Public ReadOnly Property product_used_with As String
        Get
            Return attr("product used with")
        End Get
    End Property

    Public ReadOnly Property supplier As String
        Get
            Return attr("supplier")
        End Get
    End Property

    Public ReadOnly Property bend_radius As String
        Get
            Return attr("bend radius")
        End Get
    End Property

    Public ReadOnly Property Reference_Count As Decimal
        Get
            If attr("Reference Count") Is Nothing Then
                Return CDec(1)
            Else
                Return CDec(attr("Reference Count"))
            End If
        End Get
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("attribute")>  _
    Public Property attribute() As documentConfigurationAttribute()
        Get
            Return Me.attributeField
        End Get
        Set
            Me.attributeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("document", IsNullable:=false)>  _
    Public Property references() As document()
        Get
            Return Me.referencesField
        End Get
        Set
            Me.referencesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class documentConfigurationAttribute
    
    Private nameField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class xml
    
    Private transactionsField As xmlTransactions
    
    '''<remarks/>
    Public Property transactions() As xmlTransactions
        Get
            Return Me.transactionsField
        End Get
        Set
            Me.transactionsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactions
    
    Private transactionField As xmlTransactionsTransaction
    
    '''<remarks/>
    Public Property transaction() As xmlTransactionsTransaction
        Get
            Return Me.transactionField
        End Get
        Set
            Me.transactionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransaction
    
    Private documentField() As document
    
    Private dateField As UInteger
    
    Private typeField As String
    
    Private vaultnameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("document")>  _
    Public Property document() As document()
        Get
            Return Me.documentField
        End Get
        Set
            Me.documentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property [date]() As UInteger
        Get
            Return Me.dateField
        End Get
        Set
            Me.dateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property vaultname() As String
        Get
            Return Me.vaultnameField
        End Get
        Set
            Me.vaultnameField = value
        End Set
    End Property
End Class
