'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8943
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
' "C:\Program Files\Microsoft SDKs\Windows\v6.0A\Bin\x64\xsd.exe" -lvb 
' "\\walrus\nas\PriorityMobile\Server\mefAPI\handlers\SolidWorks\SolidWorks\Resources\solidworks.xsd" 
' /out: "\\walrus\nas\PriorityMobile\Server\mefAPI\handlers\SolidWorks\SolidWorks" /c
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class xml

    Private transactionsField As xmlTransactions

    '''<remarks/>
    Public Property transactions() As xmlTransactions
        Get
            Return Me.transactionsField
        End Get
        Set
            Me.transactionsField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactions
    
    Private transactionField As xmlTransactionsTransaction
    
    '''<remarks/>
    Public Property transaction() As xmlTransactionsTransaction
        Get
            Return Me.transactionField
        End Get
        Set
            Me.transactionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransaction
    
    Private documentField As xmlTransactionsTransactionDocument
    
    Private dateField As UInteger
    
    Private typeField As String
    
    Private vaultnameField As String
    
    '''<remarks/>
    Public Property document() As xmlTransactionsTransactionDocument
        Get
            Return Me.documentField
        End Get
        Set
            Me.documentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property [date]() As UInteger
        Get
            Return Me.dateField
        End Get
        Set
            Me.dateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property vaultname() As String
        Get
            Return Me.vaultnameField
        End Get
        Set
            Me.vaultnameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransactionDocument
    
    Private configurationField As xmlTransactionsTransactionDocumentConfiguration
    
    Private aliassetField As String
    
    Private pdmweidField As UShort
    
    '''<remarks/>
    Public Property configuration() As xmlTransactionsTransactionDocumentConfiguration
        Get
            Return Me.configurationField
        End Get
        Set
            Me.configurationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property aliasset() As String
        Get
            Return Me.aliassetField
        End Get
        Set
            Me.aliassetField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property pdmweid() As UShort
        Get
            Return Me.pdmweidField
        End Get
        Set
            Me.pdmweidField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransactionDocumentConfiguration
    
    Private attributeField() As xmlTransactionsTransactionDocumentConfigurationAttribute

    Private referencesField() As xmlTransactionsTransactionDocument 'ConfigurationDocument

    Private nameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("attribute")>  _
    Public Property attribute() As xmlTransactionsTransactionDocumentConfigurationAttribute()
        Get
            Return Me.attributeField
        End Get
        Set
            Me.attributeField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("document", IsNullable:=False)>
    Public Property references() As xmlTransactionsTransactionDocument() 'ConfigurationDocument()
        Get
            Return Me.referencesField
        End Get
        Set
            Me.referencesField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransactionDocumentConfigurationAttribute
    
    Private nameField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransactionDocumentConfigurationDocument
    
    Private configurationField As xmlTransactionsTransactionDocumentConfigurationDocumentConfiguration
    
    Private aliassetField As String
    
    Private pdmweidField As UShort
    
    '''<remarks/>
    Public Property configuration() As xmlTransactionsTransactionDocumentConfigurationDocumentConfiguration
        Get
            Return Me.configurationField
        End Get
        Set
            Me.configurationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property aliasset() As String
        Get
            Return Me.aliassetField
        End Get
        Set
            Me.aliassetField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property pdmweid() As UShort
        Get
            Return Me.pdmweidField
        End Get
        Set
            Me.pdmweidField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransactionDocumentConfigurationDocumentConfiguration
    
    Private attributeField() As xmlTransactionsTransactionDocumentConfigurationDocumentConfigurationAttribute
    
    Private nameField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("attribute")>  _
    Public Property attribute() As xmlTransactionsTransactionDocumentConfigurationDocumentConfigurationAttribute()
        Get
            Return Me.attributeField
        End Get
        Set
            Me.attributeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class xmlTransactionsTransactionDocumentConfigurationDocumentConfigurationAttribute
    
    Private nameField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class
